import { FiAlertTriangle, FiCpu, FiFileText, FiMapPin, FiMessageSquare, FiSearch, FiZap } from 'react-icons/fi';

export const stats = [
  { value: '120K+', label: 'Complaints Registered', tone: 'from-sky-500 via-blue-500 to-cyan-400' },
  { value: '98K+', label: 'Resolved', tone: 'from-emerald-500 via-cyan-500 to-teal-500' },
  { value: '83%', label: 'Citizen Satisfaction', tone: 'from-amber-500 via-orange-400 to-rose-400' },
  { value: '48 hrs', label: 'Average Response', tone: 'from-slate-700 via-slate-600 to-slate-500' },
];

export const features = [
  {
    title: 'AI Complaint Classification',
    description: 'Instantly routes complaints to the right department using intelligent classification.',
    icon: FiCpu,
    route: '/features/ai-classification',
    accent: 'from-indigo-500 to-cyan-500',
  },
  {
    title: 'Live Complaint Tracking',
    description: 'Citizens can follow every movement of a complaint in real time.',
    icon: FiMapPin,
    route: '/features/live-tracking',
    accent: 'from-sky-500 to-blue-600',
    requiresAuth: true,
  },
  {
    title: 'Proof-Based Resolution',
    description: 'Each resolution is backed by photos, videos, and documentation.',
    icon: FiFileText,
    route: '/features/proof-resolution',
    accent: 'from-violet-500 to-fuchsia-500',
  },
  {
    title: 'Duplicate Detection',
    description: 'Prevent repeated submissions and improve response efficiency.',
    icon: FiSearch,
    route: '/features/duplicate-detection',
    accent: 'from-amber-500 to-orange-500',
  },
  {
    title: 'Automatic Escalation',
    description: 'Critical complaints are escalated automatically to senior officers.',
    icon: FiAlertTriangle,
    route: '/features/automatic-escalation',
    accent: 'from-emerald-500 to-cyan-500',
  },
  {
    title: 'Citizen Feedback',
    description: 'End-to-end feedback helps the administration improve public service.',
    icon: FiMessageSquare,
    route: '/features/citizen-feedback',
    accent: 'from-pink-500 to-rose-500',
  },
];

export const featureDetails = {
  aiClassification: {
    title: 'AI Complaint Classification',
    eyebrow: 'Intelligent routing',
    icon: FiCpu,
    description: 'Instantly understands the nature of a complaint and routes it to the correct department with remarkable speed.',
    overview: 'JanTrack uses contextual analysis to interpret complaint language, urgency, and location so municipal teams can act faster and with less manual triage.',
    citizenBenefit: 'Citizens receive faster acknowledgement and a clearer path to resolution.',
    governmentBenefit: 'Departments save time on intake and can focus on service delivery instead of administrative sorting.',
    howItWorks: ['Citizen submits complaint', 'System analyses complaint', 'Department assigned', 'Officer notified', 'Status updated', 'Citizen receives updates'],
    benefits: ['Faster Resolution', 'Transparency', 'Accountability', 'Real-Time Updates', 'Reduced Corruption', 'Better Citizen Trust'],
    workflow: ['Complaint', 'Verification', 'Department', 'Officer', 'Work Started', 'Proof Upload', 'Feedback', 'Closed'],
    mockItems: ['Auto-tagged urgency', 'Department match score', 'Priority queue', 'Suggested next action'],
    ctaPrimary: 'Register Complaint',
    ctaSecondary: 'Track Complaint',
    routePrimary: '/register',
    routeSecondary: '/tracking',
  },
  liveTracking: {
    title: 'Live Complaint Tracking',
    eyebrow: 'Real-time visibility',
    icon: FiMapPin,
    description: 'Citizens and officials can follow every movement of a complaint from submission to closure in real time.',
    overview: 'Each milestone is recorded, timestamped, and displayed clearly so everyone can see where a case stands without waiting for manual updates.',
    citizenBenefit: 'Citizens stay informed and trust the process because progress is visible at every stage.',
    governmentBenefit: 'Officers can coordinate more effectively and reduce delays caused by missing or unclear updates.',
    howItWorks: ['Citizen submits complaint', 'System analyses complaint', 'Department assigned', 'Officer notified', 'Status updated', 'Citizen receives updates'],
    benefits: ['Live Status', 'Fewer Follow-ups', 'Clear Ownership', 'Auditability', 'Higher Confidence', 'Faster Escalation'],
    workflow: ['Complaint', 'Verification', 'Department', 'Officer', 'Work Started', 'Proof Upload', 'Feedback', 'Closed'],
    mockItems: ['Live timeline', 'Officer assignment', 'Milestone alerts', 'Resolution evidence'],
    ctaPrimary: 'Go to Dashboard',
    ctaSecondary: 'Track Complaint',
    routePrimary: '/dashboard',
    routeSecondary: '/tracking',
    requiresAuth: true,
  },
  proofResolution: {
    title: 'Proof-Based Resolution',
    eyebrow: 'Documented outcomes',
    icon: FiFileText,
    description: 'Every action is backed by photos, videos, notes, and official updates so resolutions are evidence-based.',
    overview: 'Proof-based resolution helps teams close complaints with a complete record that can be reviewed by citizens and supervisors alike.',
    citizenBenefit: 'Citizens can see the evidence behind the final outcome and trust that the response was genuine.',
    governmentBenefit: 'Agencies reduce disputes and improve accountability by creating a reliable resolution record.',
    howItWorks: ['Citizen submits complaint', 'System analyses complaint', 'Department assigned', 'Officer notified', 'Status updated', 'Citizen receives updates'],
    benefits: ['Verifiable Evidence', 'Stronger Accountability', 'Cleaner Records', 'Improved Reviews', 'Fewer Disputes', 'Better Closure'],
    workflow: ['Complaint', 'Verification', 'Department', 'Officer', 'Work Started', 'Proof Upload', 'Feedback', 'Closed'],
    mockItems: ['Before/after media', 'Inspection notes', 'Resolution summary', 'Supporting attachment'],
    ctaPrimary: 'Register Complaint',
    ctaSecondary: 'Track Complaint',
    routePrimary: '/register',
    routeSecondary: '/tracking',
  },
  duplicateDetection: {
    title: 'Duplicate Detection',
    eyebrow: 'Smarter intake',
    icon: FiSearch,
    description: 'Identifies repeated or related submissions to prevent redundant work and improve response quality.',
    overview: 'The platform compares new complaints against existing cases to detect duplicates early and keep public service efforts focused.',
    citizenBenefit: 'Citizens avoid repeated follow-up and receive a smoother intake experience.',
    governmentBenefit: 'Teams reduce administrative noise and improve overall department efficiency.',
    howItWorks: ['Citizen submits complaint', 'System analyses complaint', 'Department assigned', 'Officer notified', 'Status updated', 'Citizen receives updates'],
    benefits: ['Reduced Noise', 'Less Duplication', 'Higher Efficiency', 'Cleaner Queue', 'Better Focus', 'Improved Trust'],
    workflow: ['Complaint', 'Verification', 'Department', 'Officer', 'Work Started', 'Proof Upload', 'Feedback', 'Closed'],
    mockItems: ['Similarity report', 'Related case list', 'Suggested merge action', 'Duplicate warning'],
    ctaPrimary: 'Register Complaint',
    ctaSecondary: 'Track Complaint',
    routePrimary: '/register',
    routeSecondary: '/tracking',
  },
  automaticEscalation: {
    title: 'Automatic Escalation',
    eyebrow: 'Priority handling',
    icon: FiAlertTriangle,
    description: 'Critical complaints are escalated to senior officers automatically when urgency thresholds are met.',
    overview: 'By identifying severity and time sensitivity, the platform ensures high-impact issues receive immediate attention.',
    citizenBenefit: 'Urgent concerns reach the right people faster and are less likely to stall.',
    governmentBenefit: 'Leadership gains visibility into critical issues and can intervene before they worsen.',
    howItWorks: ['Citizen submits complaint', 'System analyses complaint', 'Department assigned', 'Officer notified', 'Status updated', 'Citizen receives updates'],
    benefits: ['Urgent Response', 'Improved Oversight', 'Faster Intervention', 'Reduced Delay', 'Higher Accountability', 'Better Service'],
    workflow: ['Complaint', 'Verification', 'Department', 'Officer', 'Work Started', 'Proof Upload', 'Feedback', 'Closed'],
    mockItems: ['Escalation rule', 'Priority badge', 'Alert feed', 'Senior officer view'],
    ctaPrimary: 'Register Complaint',
    ctaSecondary: 'Track Complaint',
    routePrimary: '/register',
    routeSecondary: '/tracking',
  },
  citizenFeedback: {
    title: 'Citizen Feedback',
    eyebrow: 'Community trust',
    icon: FiMessageSquare,
    description: 'Collects end-to-end feedback so the administration can continuously improve public services.',
    overview: 'Feedback closes the loop between service delivery and citizen experience, helping government teams learn from each case.',
    citizenBenefit: 'Citizens can share their experience and feel that their voice is part of the improvement process.',
    governmentBenefit: 'Departments gain actionable insight into service quality and response satisfaction.',
    howItWorks: ['Citizen submits complaint', 'System analyses complaint', 'Department assigned', 'Officer notified', 'Status updated', 'Citizen receives updates'],
    benefits: ['Improved Service', 'Resident Trust', 'Actionable Insights', 'Better Communication', 'Continuous Learning', 'Higher Satisfaction'],
    workflow: ['Complaint', 'Verification', 'Department', 'Officer', 'Work Started', 'Proof Upload', 'Feedback', 'Closed'],
    mockItems: ['Feedback survey', 'Sentiment summary', 'Resolutions trend', 'Citizen comment view'],
    ctaPrimary: 'Register Complaint',
    ctaSecondary: 'Track Complaint',
    routePrimary: '/register',
    routeSecondary: '/tracking',
  },
};

export const complaintRows = [
  { id: 'JNT-1042', title: 'Road Pothole Near Market Road', department: 'Public Works', status: 'In Progress', priority: 'High', date: '2026-07-20' },
  { id: 'JNT-1045', title: 'Water Leakage in Sector 12', department: 'Water Supply', status: 'Resolved', priority: 'Medium', date: '2026-07-18' },
  { id: 'JNT-1051', title: 'Street Light Failure', department: 'Electricity', status: 'Pending', priority: 'Low', date: '2026-07-22' },
  { id: 'JNT-1060', title: 'Garbage Overflow at Bus Stand', department: 'Sanitation', status: 'Escalated', priority: 'High', date: '2026-07-24' },
];

export const timelineEvents = [
  { title: 'Complaint Submitted', date: '10 Jul 2026', officer: 'Citizen Portal', remark: 'Complaint captured successfully.' },
  { title: 'Verified', date: '11 Jul 2026', officer: 'Desk Officer', remark: 'Details matched with citizen records.' },
  { title: 'Assigned Department', date: '12 Jul 2026', officer: 'Public Works', remark: 'Allocated to field inspector.' },
  { title: 'Work Started', date: '13 Jul 2026', officer: 'Inspector Rao', remark: 'Site inspection completed.' },
  { title: 'Proof Uploaded', date: '14 Jul 2026', officer: 'Inspector Rao', remark: 'Before/after photos uploaded.' },
  { title: 'Closed', date: '15 Jul 2026', officer: 'Senior Officer', remark: 'Resolved and feedback collected.' },
];
